#ukulele:
#  redis:
#    database: 0
#    password:
#    timeout: 30
#    mode: single #sentinel/cluster/single
##    连接池
#    pool:
#      max-idle: 16
#      min-idle: 8
#      max-active: 8
#      max-wait: 3000
#      conn-timeout: 3000
#      so-timeout: 3000
#      size: 10
##    单机
#    single:
#      address: redis://127.0.0.1:6379
##    集群
#    cluster:
#      scan-interval: 1000
#      nodes:
#      read-mode: SLAVE
#      retry-attempts: 3
#      failed-attempts: 3
#      slave-connection-pool-size: 64
#      master-connection-pool-size: 64
#      retry-interval: 1500
##    哨兵
#    sentinel:
#      master: business-master
#      nodes:
#      master-onlyWrite: true
#      fail-mas: 3